name: Lint Code Base

on:
  pull_request:
    branches: [develop]

jobs:
  lint-image:
    name: Lint Code Base
    uses: swissgrc/.github/.github/workflows/lint-image.yml@64300ea603ac439c79d240c6cc89cd9f0268dcbb
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}